### ISSUE TITLE
Week 2 - Task list and issues

### ISSUE THREAD

**Issue by artanzand** [UBC-MDS/rlyrics#1]
**R** (by Thur)
- [x] #2
- [x] #3
- [x] #4
- [x] #5
- [x] #6
- [x] #7
      CONTRIBUTORS
      summary (Overview)
      bulleted list of the functions
      Python ecosystem
      Features
      Dependency
      usage
      CONDUCT.md
      CONTRIBUTING.md

**Function specifications (4 .R)**
- [x] #8
- [x] #9
- [x] #10
- [x] #11

**Comment by MacyChan** [comment]
Good job team! 2 weeks to go!
