### ISSUE TITLE
Week 3 - Task list and issues

### ISSUE THREAD

**Issue by manju-abhinandana** [UBC-MDS/rlyrics#19]
Writing functions
- [x] #20
- [x] #21
- [x] #22
- [x] #23

Testing and validation  
- [x] #24
- [x] #25
- [x] #26
- [x] #27

Others
- [x] #29
Usage, Dependancies, Download instructions from Github.  - Manju

**Comment by MacyChan** [comment]
Add kaggler to description and one more test - Manju

**Comment by manju-abhinandana** [comment]
Added Kaggler to description. 
All tests passed
Installed the package and verified if all functions works.
